import React, { useCallback, useEffect, useReducer, useRef } from "react";
import { Link } from "react-router-dom";
import { GraduationCap } from "lucide-react";
import { api } from "../../lib/api";
import ExamIntelligenceOverviewCards from "../../features/admin/exam-intelligence/ExamIntelligenceOverviewCards";
import ExamListTable from "../../features/admin/exam-intelligence/ExamListTable";
import { AdminSafetyBanner } from "../../shared/ui/core";
import { PageHeader, StatusDot } from "../../shared/ui/studyos";

const EXAM_TYPES = ["recruitment", "entrance", "certification", "opportunity", "other"];
const MANAGEMENT_MODES = ["core", "light", "index_only", "archive"];
const CADENCES = ["annual", "recurring", "irregular", "one_off", "unknown"];

const INITIAL_FILTERS = { search: "", examType: "", isActive: "", managementMode: "", cadence: "", page: 0 };

function filtersReducer(state, action) {
  switch (action.type) {
    case "SET_FILTER":
      return { ...state, [action.key]: action.value, page: 0 };
    case "SET_PAGE":
      return { ...state, page: action.page };
    default:
      return state;
  }
}

const TABS = [
  { id: "overview", label: "Overview" },
  { id: "exams", label: "Exams" },
];

const TAB_HELPER_COPY = {
  overview: "Snapshot of verified exam intelligence.",
  exams: "Exams visible to users come from this list.",
};

const PAGE_SIZE = 25;

export default function AdminExamIntelligence() {
  const [tab, setTab] = React.useState("overview");

  const [overview, setOverview] = React.useState(null);
  const [overviewError, setOverviewError] = React.useState("");

  const [exams, setExams] = React.useState({ items: [], count: 0, total_count: 0, has_next: false, limit: PAGE_SIZE, offset: 0 });
  const [examsStatus, setExamsStatus] = React.useState("idle"); // idle | loading | data | empty | error
  const [examsError, setExamsError] = React.useState("");

  const [filters, dispatch] = useReducer(filtersReducer, INITIAL_FILTERS);
  const { search, examType: examTypeFilter, isActive: isActiveFilter, page } = filters;

  // Monotonic sequence to discard stale API responses.
  const seqRef = useRef(0);

  const loadOverview = useCallback(async () => {
    setOverviewError("");
    try {
      const d = await api.get("/api/admin/exam-intelligence/overview");
      setOverview(d);
    } catch (e) {
      setOverviewError(e?.message || "Could not load overview");
    }
  }, []);

  const loadExams = useCallback(async (f) => {
    const { search: q, examType: et, isActive: ia, managementMode: mm, cadence: cad, page: pg } = f;
    const offset = pg * PAGE_SIZE;
    const qs = new URLSearchParams({ limit: String(PAGE_SIZE), offset: String(offset) });
    if (q.trim()) qs.set("q", q.trim());
    if (et) qs.set("exam_type", et);
    if (ia === "true") qs.set("is_active", "true");
    else if (ia === "false") qs.set("is_active", "false");
    if (mm) qs.set("management_mode", mm);
    if (cad) qs.set("cadence", cad);

    const mySeq = ++seqRef.current;
    setExamsStatus("loading");
    setExamsError("");
    try {
      const d = await api.get(`/api/admin/exam-intelligence/exams?${qs}`);
      if (mySeq !== seqRef.current) return;
      const items = d?.items || [];
      setExams({
        items,
        count: d?.count ?? items.length,
        total_count: d?.total_count ?? items.length,
        has_next: d?.has_next ?? false,
        limit: d?.limit ?? PAGE_SIZE,
        offset: d?.offset ?? offset,
      });
      setExamsStatus(items.length ? "data" : "empty");
    } catch (e) {
      if (mySeq !== seqRef.current) return;
      setExamsError(e?.message || "Could not load exams");
      setExamsStatus("error");
    }
  }, []);

  useEffect(() => {
    if (tab === "overview") loadOverview();
  }, [tab, loadOverview]);

  useEffect(() => {
    if (tab === "exams") loadExams(filters);
  }, [tab, filters, loadExams]);

  const handlePageChange = useCallback((next) => dispatch({ type: "SET_PAGE", page: next }), []);

  const isLoading = examsStatus === "loading";

  return (
    <div className="space-y-6" data-testid="admin-exam-intelligence-page">
      <PageHeader
        eyebrow={
          <span className="inline-flex items-center gap-2">
            <GraduationCap className="h-3.5 w-3.5" /> Exam intelligence · internal
          </span>
        }
        title="Exam Intelligence Review"
        sub={
          <>
            Move syllabus mentions and PYQ tags into <em>verified</em> only after checking an
            admin-reviewed source. Nothing on this page is generated by AI.
          </>
        }
        right={
          <span className="inline-flex items-center gap-2">
            <Link
              to="/admin/exam-intelligence/cms"
              className="btn btn-ghost text-xs"
              data-testid="exam-intel-cms-link"
            >
              Create / Import CMS
            </Link>
            <StatusDot state="live" label="Live · /api/admin/exam-intelligence" />
          </span>
        }
      />

      <AdminSafetyBanner
        title="Verified-only contract"
        testId="admin-exam-intel-safety"
        tone="clay"
      >
        User-facing exam intelligence (Study OS today view) reads only rows
        you've marked <span className="font-mono">verified</span> or{" "}
        <span className="font-mono">locked</span>. Pending and rejected rows
        never reach the aspirant. No AI is used to generate, interpret, or
        auto-verify these rows — your judgement is the source of truth.
      </AdminSafetyBanner>

      <nav
        className="flex flex-wrap gap-1 bg-[#F3EADB] p-1 rounded-full border border-[#E7DECB] w-fit"
        aria-label="Exam intelligence tabs"
      >
        {TABS.map((t) => (
          <button
            key={t.id}
            type="button"
            onClick={() => setTab(t.id)}
            data-testid={`exam-intel-tab-${t.id}`}
            className={`px-3.5 py-1.5 rounded-full text-[12px] font-semibold transition ${
              tab === t.id
                ? "bg-[#FFFDF9] text-[#2E2218] border border-[#D9C7A7]"
                : "text-clay-700 hover:bg-[#E7D6BA]"
            }`}
            aria-pressed={tab === t.id}
          >
            {t.label}
          </button>
        ))}
      </nav>

      {TAB_HELPER_COPY[tab] ? (
        <p
          className="text-xs text-muted-foreground"
          data-testid={`exam-intel-tab-helper-${tab}`}
        >
          {TAB_HELPER_COPY[tab]}
        </p>
      ) : null}

      {tab === "overview" ? (
        <section>
          {overviewError ? (
            <div className="rounded-xl bg-dusk-50 text-dusk-800 text-xs px-3 py-2 mb-3">
              {overviewError}
            </div>
          ) : null}
          <ExamIntelligenceOverviewCards overview={overview} />
        </section>
      ) : null}

      {tab === "exams" ? (
        <section className="space-y-3">
          <div className="flex flex-wrap items-center gap-2">
            <input
              type="search"
              placeholder="Search name or slug…"
              value={search}
              onChange={(e) => dispatch({ type: "SET_FILTER", key: "search", value: e.target.value })}
              className="input input-sm w-48"
              data-testid="exam-intel-search"
              aria-label="Search exams"
            />
            <select
              value={examTypeFilter}
              onChange={(e) => dispatch({ type: "SET_FILTER", key: "examType", value: e.target.value })}
              className="select select-sm w-40"
              data-testid="exam-intel-type-filter"
              aria-label="Filter by exam type"
            >
              <option value="">All types</option>
              {EXAM_TYPES.map((t) => (
                <option key={t} value={t}>{t}</option>
              ))}
            </select>
            <select
              value={isActiveFilter}
              onChange={(e) => dispatch({ type: "SET_FILTER", key: "isActive", value: e.target.value })}
              className="select select-sm w-28"
              data-testid="exam-intel-active-filter"
              aria-label="Filter by active status"
            >
              <option value="">All</option>
              <option value="true">Active</option>
              <option value="false">Inactive</option>
            </select>
            <select
              value={filters.managementMode}
              onChange={(e) => dispatch({ type: "SET_FILTER", key: "managementMode", value: e.target.value })}
              className="select select-sm w-44"
              data-testid="exam-intel-lane-filter"
              aria-label="Filter by management mode"
            >
              <option value="">All (non-archive)</option>
              {MANAGEMENT_MODES.map((m) => (
                <option key={m} value={m}>{m}</option>
              ))}
            </select>
            <select
              value={filters.cadence}
              onChange={(e) => dispatch({ type: "SET_FILTER", key: "cadence", value: e.target.value })}
              className="select select-sm w-36"
              data-testid="exam-intel-cadence-filter"
              aria-label="Filter by cadence"
            >
              <option value="">All cadences</option>
              {CADENCES.map((c) => (
                <option key={c} value={c}>{c}</option>
              ))}
            </select>
            <div className="ml-auto flex items-center gap-2">
              {examsStatus !== "idle" && (
                <p className="text-xs text-muted-foreground" data-testid="exam-intel-count-label">
                  {exams.total_count} exam{exams.total_count === 1 ? "" : "s"}
                  {exams.total_count !== exams.count && exams.count > 0
                    ? ` · showing ${exams.offset + 1}–${Math.max(exams.offset + 1, exams.offset + exams.count)}`
                    : ""}
                </p>
              )}
              <button
                type="button"
                onClick={() => loadExams(filters)}
                className="btn btn-ghost text-xs"
                data-testid="exam-intel-refresh"
              >
                {isLoading ? "Loading…" : "Refresh"}
              </button>
            </div>
          </div>

          {examsStatus === "error" && (
            <div
              className="rounded-xl bg-dusk-50 text-dusk-800 text-xs px-3 py-2"
              data-testid="exam-intel-error"
            >
              {examsError}
            </div>
          )}

          {examsStatus === "loading" && (
            <div className="text-xs text-muted-foreground py-4" data-testid="exam-intel-loading">
              Loading…
            </div>
          )}

          {(examsStatus === "data" || examsStatus === "empty") && (
            <ExamListTable
              items={exams.items}
              page={page}
              pageSize={PAGE_SIZE}
              total_count={exams.total_count}
              has_next={exams.has_next}
              offset={exams.offset}
              onPageChange={handlePageChange}
            />
          )}
        </section>
      ) : null}
    </div>
  );
}
