import React, { useCallback, useEffect, useState } from "react";
import { GraduationCap } from "lucide-react";
import { api } from "../../lib/api";
import ExamIntelligenceOverviewCards from "../../features/admin/exam-intelligence/ExamIntelligenceOverviewCards";
import ExamListTable from "../../features/admin/exam-intelligence/ExamListTable";
import { AdminSafetyBanner } from "../../shared/ui/core";
import { PageHeader, StatusDot } from "../../shared/ui/studyos";

const TABS = [
  { id: "overview", label: "Overview" },
  { id: "exams", label: "Exams" },
];

const TAB_HELPER_COPY = {
  overview: "Snapshot of verified exam intelligence.",
  exams: "Exams visible to users come from this list.",
};

export default function AdminExamIntelligence() {
  const [tab, setTab] = useState("overview");

  const [overview, setOverview] = useState(null);
  const [overviewError, setOverviewError] = useState("");

  const [exams, setExams] = useState({ items: [], count: 0 });
  const [examsLoading, setExamsLoading] = useState(false);

  const loadOverview = useCallback(async () => {
    setOverviewError("");
    try {
      const d = await api.get("/api/admin/exam-intelligence/overview");
      setOverview(d);
    } catch (e) {
      setOverviewError(e?.message || "Could not load overview");
    }
  }, []);

  const loadExams = useCallback(async () => {
    setExamsLoading(true);
    try {
      const d = await api.get("/api/admin/exam-intelligence/exams?limit=200");
      setExams({ items: d?.items || [], count: d?.count || 0 });
    } catch {
      setExams({ items: [], count: 0 });
    } finally {
      setExamsLoading(false);
    }
  }, []);

  useEffect(() => {
    if (tab === "overview") loadOverview();
    if (tab === "exams") loadExams();
  }, [tab, loadOverview, loadExams]);

  return (
    <div className="space-y-6" data-testid="admin-exam-intelligence-page">
      <PageHeader
        eyebrow={
          <span className="inline-flex items-center gap-2">
            <GraduationCap className="h-3.5 w-3.5" /> Exam intelligence · internal
          </span>
        }
        title="Exam Intelligence Review"
        sub={
          <>
            Move syllabus mentions and PYQ tags into <em>verified</em> only after checking an
            admin-reviewed source. Nothing on this page is generated by AI.
          </>
        }
        right={<StatusDot state="live" label="Live · /api/admin/exam-intelligence" />}
      />

      <AdminSafetyBanner
        title="Verified-only contract"
        testId="admin-exam-intel-safety"
        tone="clay"
      >
        User-facing exam intelligence (Study OS today view) reads only rows
        you've marked <span className="font-mono">verified</span> or{" "}
        <span className="font-mono">locked</span>. Pending and rejected rows
        never reach the aspirant. No AI is used to generate, interpret, or
        auto-verify these rows — your judgement is the source of truth.
      </AdminSafetyBanner>

      <nav
        className="flex flex-wrap gap-1 bg-[#F3EADB] p-1 rounded-full border border-[#E7DECB] w-fit"
        aria-label="Exam intelligence tabs"
      >
        {TABS.map((t) => (
          <button
            key={t.id}
            type="button"
            onClick={() => setTab(t.id)}
            data-testid={`exam-intel-tab-${t.id}`}
            className={`px-3.5 py-1.5 rounded-full text-[12px] font-semibold transition ${
              tab === t.id
                ? "bg-[#FFFDF9] text-[#2E2218] border border-[#D9C7A7]"
                : "text-clay-700 hover:bg-[#E7D6BA]"
            }`}
            aria-pressed={tab === t.id}
          >
            {t.label}
          </button>
        ))}
      </nav>

      {TAB_HELPER_COPY[tab] ? (
        <p
          className="text-xs text-muted-foreground"
          data-testid={`exam-intel-tab-helper-${tab}`}
        >
          {TAB_HELPER_COPY[tab]}
        </p>
      ) : null}

      {tab === "overview" ? (
        <section>
          {overviewError ? (
            <div className="rounded-xl bg-dusk-50 text-dusk-800 text-xs px-3 py-2 mb-3">
              {overviewError}
            </div>
          ) : null}
          <ExamIntelligenceOverviewCards overview={overview} />
        </section>
      ) : null}

      {tab === "exams" ? (
        <section className="space-y-3">
          <div className="flex items-center justify-between">
            <p className="text-xs text-muted-foreground">
              {exams.count} exam{exams.count === 1 ? "" : "s"} registered.
            </p>
            <button type="button" onClick={loadExams} className="btn btn-ghost text-xs">
              {examsLoading ? "Loading…" : "Refresh"}
            </button>
          </div>
          <ExamListTable items={exams.items} />
        </section>
      ) : null}
    </div>
  );
}
