import React, { useCallback, useEffect, useReducer, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { GraduationCap } from "lucide-react";
import { api } from "../../lib/api";
import ExamIntelligenceOverviewCards from "../../features/admin/exam-intelligence/ExamIntelligenceOverviewCards";
import ExamListTable from "../../features/admin/exam-intelligence/ExamListTable";
import {
  BUSINESS_PRIORITY_LABELS,
  CADENCE_LABELS,
  EXAM_PURPOSE_LABELS,
} from "../../features/admin/exam-intelligence/ExamIntelGlossary";
import { AdminSafetyBanner } from "../../shared/ui/core";
import { PageHeader, StatusDot } from "../../shared/ui/studyos";

const INITIAL_FILTERS = {
  search: "",
  examType: "",
  activeState: "active",
  managementMode: "",
  cadence: "",
  examFamilyId: "",
  page: 0,
};

function filtersReducer(state, action) {
  switch (action.type) {
    case "SET_FILTER":
      return { ...state, [action.key]: action.value, page: 0 };
    case "SET_PAGE":
      return { ...state, page: action.page };
    default:
      return state;
  }
}

const TABS = [
  { id: "overview", label: "Overview" },
  { id: "exams", label: "Exams" },
];

const TAB_HELPER_COPY = {
  overview: "Snapshot of reviewed and locked exam intelligence.",
  exams: "Exams visible to users come from this list.",
};

const PAGE_SIZE = 25;

export default function AdminExamIntelligence() {
  const [tab, setTab] = React.useState("overview");

  const [overview, setOverview] = React.useState(null);
  const [overviewError, setOverviewError] = React.useState("");

  const [exams, setExams] = React.useState({ items: [], count: 0, total_count: 0, has_next: false, limit: PAGE_SIZE, offset: 0 });
  const [examsStatus, setExamsStatus] = React.useState("idle"); // idle | loading | data | empty | error
  const [examsError, setExamsError] = React.useState("");

  const [families, setFamilies] = useState([]);
  useEffect(() => {
    // Non-blocking background fetch — background read, not a mutation.
    api.get("/api/admin/exam-intelligence-cms/exam-families?is_active=true&limit=200")
      .then((d) => setFamilies(d?.items || []))
      .catch(() => {});
  }, []);

  const [filters, dispatch] = useReducer(filtersReducer, INITIAL_FILTERS);
  const { search, examType: examTypeFilter, page } = filters;

  // Monotonic sequence to discard stale API responses.
  const seqRef = useRef(0);

  const loadOverview = useCallback(async () => {
    setOverviewError("");
    try {
      const d = await api.get("/api/admin/exam-intelligence/overview");
      setOverview(d);
    } catch (e) {
      setOverviewError(e?.message || "Could not load overview");
    }
  }, []);

  const loadExams = useCallback(async (f) => {
    const { search: q, examType: et, activeState: as_, managementMode: mm, cadence: cad, examFamilyId: efid, page: pg } = f;
    const offset = pg * PAGE_SIZE;
    const qs = new URLSearchParams({ limit: String(PAGE_SIZE), offset: String(offset) });
    if (q.trim()) qs.set("q", q.trim());
    if (et) qs.set("exam_type", et);
    if (as_) qs.set("active_state", as_);
    if (mm) qs.set("management_mode", mm);
    if (cad) qs.set("cadence", cad);
    if (efid) qs.set("exam_family_id", efid);

    const mySeq = ++seqRef.current;
    setExamsStatus("loading");
    setExamsError("");
    try {
      const d = await api.get(`/api/admin/exam-intelligence/exams?${qs}`);
      if (mySeq !== seqRef.current) return;
      const items = d?.items || [];
      setExams({
        items,
        count: d?.count ?? items.length,
        total_count: d?.total_count ?? items.length,
        has_next: d?.has_next ?? false,
        limit: d?.limit ?? PAGE_SIZE,
        offset: d?.offset ?? offset,
      });
      setExamsStatus(items.length ? "data" : "empty");
    } catch (e) {
      if (mySeq !== seqRef.current) return;
      setExamsError(e?.message || "Could not load exams");
      setExamsStatus("error");
    }
  }, []);

  useEffect(() => {
    if (tab === "overview") loadOverview();
  }, [tab, loadOverview]);

  useEffect(() => {
    if (tab === "exams") loadExams(filters);
  }, [tab, filters, loadExams]);

  const handlePageChange = useCallback((next) => dispatch({ type: "SET_PAGE", page: next }), []);

  const isLoading = examsStatus === "loading";

  return (
    <div className="space-y-6" data-testid="admin-exam-intelligence-page">
      <PageHeader
        eyebrow={
          <span className="inline-flex items-center gap-2">
            <GraduationCap className="h-3.5 w-3.5" /> Exam intelligence · internal
          </span>
        }
        title="Exam Registry"
        sub={
          <>
            Move coverage rows to <em>reviewed</em> or <em>locked</em>, and PYQ questions to <em>verified</em>, only after checking an
            admin-reviewed source. Nothing on this page is generated by AI.
          </>
        }
        right={
          <span className="inline-flex items-center gap-2 flex-wrap justify-end">
            <Link
              to="/admin/exam-intelligence/console"
              className="btn btn-primary text-xs"
              data-testid="registry-open-console"
            >
              Open console
            </Link>
            <Link
              to="/admin/exam-intelligence/new"
              className="btn btn-ghost text-xs"
              data-testid="registry-create-exam"
            >
              Create exam
            </Link>
            <Link
              to="/admin/exam-intelligence/cms"
              className="btn btn-ghost text-xs text-amber-700 border border-amber-300/70"
              data-testid="registry-advanced-cms"
              title="Low-level repair / bulk import — power users only"
            >
              Advanced import / repair
            </Link>
            <StatusDot state="live" label="Live" />
          </span>
        }
      />

      <AdminSafetyBanner
        title="Lifecycle-gated contract"
        testId="admin-exam-intel-safety"
        tone="clay"
        collapsible
        defaultOpen={false}
      >
        User-facing exam intelligence (Study OS today view) reads only rows at
        the right lifecycle stage:{" "}
        <span className="font-mono">reviewed</span> or{" "}
        <span className="font-mono">locked</span> for coverage rows;{" "}
        <span className="font-mono">verified</span> for PYQ questions.
        Pending and rejected rows never reach the aspirant. No AI is used to
        generate, interpret, or auto-approve these rows — your judgement is the
        source of truth.
      </AdminSafetyBanner>

      <nav
        className="flex flex-wrap gap-1 bg-[#F3EADB] p-1 rounded-full border border-[#E7DECB] w-fit"
        aria-label="Exam intelligence tabs"
      >
        {TABS.map((t) => (
          <button
            key={t.id}
            type="button"
            onClick={() => setTab(t.id)}
            data-testid={`exam-intel-tab-${t.id}`}
            className={`px-3.5 py-1.5 rounded-full text-[12px] font-semibold transition ${
              tab === t.id
                ? "bg-[#FFFDF9] text-[#2E2218] border border-[#D9C7A7]"
                : "text-clay-700 hover:bg-[#E7D6BA]"
            }`}
            aria-pressed={tab === t.id}
          >
            {t.label}
          </button>
        ))}
      </nav>

      {TAB_HELPER_COPY[tab] ? (
        <p
          className="text-xs text-muted-foreground"
          data-testid={`exam-intel-tab-helper-${tab}`}
        >
          {TAB_HELPER_COPY[tab]}
        </p>
      ) : null}

      {tab === "overview" ? (
        <section>
          {overviewError ? (
            <div className="rounded-xl bg-dusk-50 text-dusk-800 text-xs px-3 py-2 mb-3">
              {overviewError}
            </div>
          ) : null}
          <ExamIntelligenceOverviewCards overview={overview} />
        </section>
      ) : null}

      {tab === "exams" ? (
        <section className="space-y-3">
          <div className="flex flex-wrap items-center gap-2">
            <input
              type="search"
              placeholder="Search name or slug…"
              value={search}
              onChange={(e) => dispatch({ type: "SET_FILTER", key: "search", value: e.target.value })}
              className="input input-sm w-48"
              data-testid="exam-intel-search"
              aria-label="Search exams"
            />
            <select
              value={examTypeFilter}
              onChange={(e) => dispatch({ type: "SET_FILTER", key: "examType", value: e.target.value })}
              className="select select-sm w-44"
              data-testid="exam-intel-type-filter"
              aria-label="Filter by exam purpose"
            >
              <option value="">All purposes</option>
              {Object.entries(EXAM_PURPOSE_LABELS).map(([k, { label }]) => (
                <option key={k} value={k}>{label}</option>
              ))}
            </select>
            <select
              value={filters.activeState}
              onChange={(e) => dispatch({ type: "SET_FILTER", key: "activeState", value: e.target.value })}
              className="select select-sm w-28"
              data-testid="exam-intel-active-filter"
              aria-label="Filter by active status"
            >
              <option value="active">Active</option>
              <option value="inactive">Inactive</option>
              <option value="all">All</option>
            </select>
            {families.length > 0 && (
              <select
                value={filters.examFamilyId}
                onChange={(e) => dispatch({ type: "SET_FILTER", key: "examFamilyId", value: e.target.value })}
                className="select select-sm w-44"
                data-testid="exam-intel-family-filter"
                aria-label="Filter by exam family"
              >
                <option value="">All families</option>
                {families.map((f) => (
                  <option key={f.id} value={f.id}>{f.name}</option>
                ))}
              </select>
            )}
            <select
              value={filters.managementMode}
              onChange={(e) => dispatch({ type: "SET_FILTER", key: "managementMode", value: e.target.value })}
              className="select select-sm w-44"
              data-testid="exam-intel-lane-filter"
              aria-label="Filter by business priority"
            >
              <option value="">All (non-archive)</option>
              {Object.entries(BUSINESS_PRIORITY_LABELS)
                .filter(([k]) => k !== "null")
                .map(([k, { label }]) => (
                  <option key={k} value={k}>{label}</option>
                ))}
              <option value="__null__">{BUSINESS_PRIORITY_LABELS.null.label}</option>
            </select>
            <select
              value={filters.cadence}
              onChange={(e) => dispatch({ type: "SET_FILTER", key: "cadence", value: e.target.value })}
              className="select select-sm w-36"
              data-testid="exam-intel-cadence-filter"
              aria-label="Filter by cadence"
            >
              <option value="">All cadences</option>
              {Object.entries(CADENCE_LABELS).map(([k, label]) => (
                <option key={k} value={k}>{label}</option>
              ))}
            </select>
            <div className="ml-auto flex items-center gap-2">
              {examsStatus !== "idle" && (
                <p className="text-xs text-muted-foreground" data-testid="exam-intel-count-label">
                  {exams.total_count} exam{exams.total_count === 1 ? "" : "s"}
                  {exams.total_count !== exams.count && exams.count > 0
                    ? ` · showing ${exams.offset + 1}–${Math.max(exams.offset + 1, exams.offset + exams.count)}`
                    : ""}
                </p>
              )}
              <button
                type="button"
                onClick={() => loadExams(filters)}
                className="btn btn-ghost text-xs"
                data-testid="exam-intel-refresh"
              >
                {isLoading ? "Loading…" : "Refresh"}
              </button>
            </div>
          </div>

          {examsStatus === "error" && (
            <div
              className="rounded-xl bg-dusk-50 text-dusk-800 text-xs px-3 py-2"
              data-testid="exam-intel-error"
            >
              {examsError}
            </div>
          )}

          {examsStatus === "loading" && (
            <div className="text-xs text-muted-foreground py-4" data-testid="exam-intel-loading">
              Loading…
            </div>
          )}

          {(examsStatus === "data" || examsStatus === "empty") && (
            <ExamListTable
              items={exams.items}
              page={page}
              pageSize={PAGE_SIZE}
              total_count={exams.total_count}
              has_next={exams.has_next}
              offset={exams.offset}
              onPageChange={handlePageChange}
            />
          )}
        </section>
      ) : null}
    </div>
  );
}
