-- Microtopic renames and study-source pointers for UPSC GS.
--
-- Names moved to vocabulary aspirants already recognise: NCERT chapter and
-- subhead titles where a textbook covers the topic, plain exam vocabulary where
-- none does. Ids are unchanged, so nothing referencing a microtopic breaks.
--
-- metadata.study_sources is guidance, not provenance. It does not claim a
-- question was set from that chapter; it says this is where the syllabus a
-- candidate has already read connects to what the exam asks. Chapter TITLES are
-- stored rather than numbers, because NCERT renumbers between editions.
--
-- 233 renamed or sourced, 1 deactivated.

BEGIN;

-- Abort if any id prefix is ambiguous or missing.
DO $$
DECLARE bad int;
BEGIN
  SELECT count(*) INTO bad FROM (VALUES
    ('f0f5a7e3'),
    ('cf0855dd'),
    ('fe6538f3'),
    ('acd9d6ba'),
    ('01d8cbbc'),
    ('90933549'),
    ('2acb3c6d'),
    ('04b86c54'),
    ('59cdec61'),
    ('e9f28928'),
    ('be78492d'),
    ('99998dde'),
    ('42380d00'),
    ('7a9ef97f'),
    ('b9fd43a1'),
    ('a6df38b4'),
    ('89b9d2cb'),
    ('5a9e3e5b'),
    ('50c227c7'),
    ('4bb3306d'),
    ('564b065b'),
    ('cb0b98ec'),
    ('9cb05e22'),
    ('98ad1c9d'),
    ('9b6155ff'),
    ('741b1b26'),
    ('69f5f696'),
    ('9a41122b'),
    ('75ca9347'),
    ('db700d76'),
    ('1e6c07b8'),
    ('b75efc14'),
    ('7110e9d8'),
    ('0ebbb2b4'),
    ('c84898db'),
    ('0ad674a9'),
    ('7125cf43'),
    ('05a42bff'),
    ('601b76a3'),
    ('758fb132'),
    ('89f9867d'),
    ('07d0f9f8'),
    ('21e5e3a1'),
    ('8c9499a4'),
    ('c04bfe17'),
    ('33a6cc51'),
    ('ef19b179'),
    ('1dd4bd6f'),
    ('6fa3309d'),
    ('63ae071a'),
    ('b0e9c565'),
    ('6fe2005c'),
    ('7633e848'),
    ('180a9b2f'),
    ('347ca3d5'),
    ('520ffe2a'),
    ('fdc986d4'),
    ('1afc4357'),
    ('7f08042b'),
    ('e4c262b4'),
    ('3fcb6de8'),
    ('66a6ed8a'),
    ('796be476'),
    ('4961002d'),
    ('e1a5612a'),
    ('03bdd74d'),
    ('b9e2268e'),
    ('2f44b4db'),
    ('93e6b74b'),
    ('9a055491'),
    ('523f626e'),
    ('7556e6ac'),
    ('6cfd3c3c'),
    ('87041523'),
    ('eaacf60f'),
    ('b93c6ca1'),
    ('aa8350fa'),
    ('7f80d70d'),
    ('9d62b3a9'),
    ('ace3fd37'),
    ('ac36747a'),
    ('0cabc0e9'),
    ('ebe20275'),
    ('e468d421'),
    ('8b0d90c2'),
    ('9b419dbd'),
    ('ca69ea82'),
    ('913b826e'),
    ('c8d9194d'),
    ('e3cf11b7'),
    ('5a8bc4f5'),
    ('ef2163b5'),
    ('6b2ca3a8'),
    ('84bc27b9'),
    ('58c3f676'),
    ('1d225731'),
    ('bd9085aa'),
    ('512e8c00'),
    ('4af21078'),
    ('5cd4d5a6'),
    ('88219a6b'),
    ('1cd9949b'),
    ('64bfe1f1'),
    ('93e92dcb'),
    ('1722f5df'),
    ('9ef945d6'),
    ('93929d93'),
    ('586d5666'),
    ('f75261c6'),
    ('4d279345'),
    ('a1896442'),
    ('cb50b194'),
    ('11f635d2'),
    ('37160da9'),
    ('bb64c318'),
    ('be28bc4d'),
    ('8b8d195d'),
    ('ae7b07ac'),
    ('cbb792cd'),
    ('4ff96891'),
    ('31f1d931'),
    ('a4b0c3b7'),
    ('66802b7b'),
    ('2ccca1e9'),
    ('6be63a96'),
    ('daa689f2'),
    ('1f90fbbf'),
    ('31cf0e35'),
    ('3e240607'),
    ('971a22b9'),
    ('29af2935'),
    ('69b0ea72'),
    ('8c060e1c'),
    ('8713e217'),
    ('2192efc2'),
    ('7889a551'),
    ('2707150a'),
    ('10e4c33b'),
    ('a8939b7e'),
    ('3ea83231'),
    ('8f635c62'),
    ('f5ad1028'),
    ('5767d76c'),
    ('3860384c'),
    ('4ae1a175'),
    ('3d5f609a'),
    ('071d0c52'),
    ('624b9c56'),
    ('9b05314d'),
    ('f21ab90d'),
    ('3b0a64fd'),
    ('26c18d07'),
    ('64bfd004'),
    ('598d7ce8'),
    ('c06dd0e0'),
    ('2c510a52'),
    ('8f03c3e9'),
    ('b2f1e8ea'),
    ('0e80d2a1'),
    ('61120bdd'),
    ('9f62ad97'),
    ('48f9772e'),
    ('71716840'),
    ('d6152647'),
    ('77b2c28a'),
    ('9831ee26'),
    ('803e588e'),
    ('faae405c'),
    ('8e834bd5'),
    ('ee473b0f'),
    ('e50a7e81'),
    ('cb6b1afa'),
    ('3c34cf1b'),
    ('61e36414'),
    ('07148e1a'),
    ('228a5283'),
    ('15624d65'),
    ('d824c6e9'),
    ('5d61a8fd'),
    ('74a4adff'),
    ('cea3c9c5'),
    ('a218d1ba'),
    ('a4d2c72a'),
    ('59a26ffc'),
    ('cc133a7d'),
    ('5b00d743'),
    ('f04a60bb'),
    ('a7c38826'),
    ('4971ff36'),
    ('47dcedf5'),
    ('39f1a761'),
    ('21c46069'),
    ('bd5847e7'),
    ('e57ad5b3'),
    ('ede5a5e1'),
    ('15936c3d'),
    ('2f1b7047'),
    ('5858c30e'),
    ('e2e8bf83'),
    ('9ae14a1c'),
    ('e5a97b06'),
    ('3e99163e'),
    ('ae80b3ab'),
    ('814ac6fd'),
    ('692609bc'),
    ('1abf068e'),
    ('de8ab3b1'),
    ('fca7b5dd'),
    ('cd941d98'),
    ('47eba1b6'),
    ('40bf511c'),
    ('5849c447'),
    ('bac98697'),
    ('ffb14933'),
    ('6c1b6671'),
    ('49b4790b'),
    ('a6999dcd'),
    ('f732797f'),
    ('ee6c5c2b'),
    ('f087e4aa'),
    ('93bda482'),
    ('f87ee241'),
    ('fa11b813'),
    ('1af4be87'),
    ('bbf61f1e'),
    ('edb85caf'),
    ('cebc029d'),
    ('9287d12d'),
    ('e336caf3'),
    ('b56a807c'),
    ('69cb3017'),
    ('2d384e36'),
    ('ca4c910c'),
    ('87385709')
  ) AS v(prefix)
  WHERE (SELECT count(*) FROM public.topics t
         WHERE t.id::text LIKE v.prefix || '%'
           AND t.level = 'microtopic') <> 1;
  IF bad > 0 THEN
    RAISE EXCEPTION 'id prefix does not resolve to exactly one microtopic: % rows', bad;
  END IF;
END $$;

UPDATE public.topics t SET
  name = v.name,
  slug = v.slug,
  metadata = t.metadata || jsonb_build_object('study_sources', v.sources)
FROM (VALUES
  ('f0f5a7e3', 'Energy flow and ecological pyramids', 'gs-energy-flow-and-ecological-pyramids-bf05b3e7', '[{"type": "ncert", "ref": "Class 12 Biology — Ecosystem"}, {"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('cf0855dd', 'Population interactions', 'gs-population-interactions-28cd1a4b', '[{"type": "ncert", "ref": "Class 12 Biology — Organisms and Populations"}, {"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('fe6538f3', 'Habitat, niche and adaptations', 'gs-habitat-niche-and-adaptations-baaaa2b6', '[{"type": "ncert", "ref": "Class 12 Biology — Organisms and Populations"}, {"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('acd9d6ba', 'Ecosystems and their types', 'gs-ecosystems-and-their-types-d02b6ab8', '[{"type": "ncert", "ref": "Class 12 Biology — Ecosystem"}, {"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('01d8cbbc', 'Nutrient cycles and decomposition', 'gs-nutrient-cycles-and-decomposition-e70bf228', '[{"type": "ncert", "ref": "Class 12 Biology — Ecosystem"}, {"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('90933549', 'Indian fauna and endemic species', 'gs-indian-fauna-and-endemic-species-bafcb0a1', '[{"type": "standard", "ref": "Shankar IAS Environment"}, {"type": "standard", "ref": "WII species profiles"}]'::jsonb),
  ('2acb3c6d', 'Indian flora and forest produce', 'gs-indian-flora-and-forest-produce-33430ed2', '[{"type": "standard", "ref": "India State of Forest Report"}]'::jsonb),
  ('04b86c54', 'Alien species invasion', 'gs-alien-species-invasion-b51221d7', '[{"type": "ncert", "ref": "Class 12 Biology — Biodiversity and Conservation"}, {"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('59cdec61', 'Loss of biodiversity', 'gs-loss-of-biodiversity-a71e9aec', '[{"type": "ncert", "ref": "Class 12 Biology — Biodiversity and Conservation"}, {"type": "standard", "ref": "IUCN Red List"}, {"type": "standard", "ref": "Shankar IAS"}]'::jsonb),
  ('e9f28928', 'Marine ecosystems and coral reefs', 'gs-marine-ecosystems-and-coral-reefs-43c8af67', '[{"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('be78492d', 'Wetlands and Ramsar sites', 'gs-wetlands-and-ramsar-sites-c2542357', '[{"type": "standard", "ref": "Shankar IAS Environment"}, {"type": "standard", "ref": "Ramsar site list"}]'::jsonb),
  ('99998dde', 'In-situ conservation: parks and sanctuaries', 'gs-in-situ-conservation-parks-and-sanctuaries-3683beef', '[{"type": "ncert", "ref": "Class 12 Biology — Biodiversity and Conservation"}, {"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('42380d00', 'Wildlife Protection Act', 'gs-wildlife-protection-act-5a9c0e5c', '[{"type": "standard", "ref": "Bare Act"}, {"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('7a9ef97f', 'Forest laws and forest rights', 'gs-forest-laws-and-forest-rights-f4bc8077', '[{"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('b9fd43a1', 'Environment Protection Act and pollution control bodies', 'gs-environment-protection-act-and-pollution-control-bodies-ded92522', '[{"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('a6df38b4', 'Biological Diversity Act, BMCs and Nagoya Protocol', 'gs-biological-diversity-act-bmcs-and-nagoya-protocol-79809fce', '[{"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('89b9d2cb', 'Air pollution and its control', 'gs-air-pollution-and-its-control-afb18bca', '[{"type": "ncert", "ref": "Class 12 Biology — Environmental Issues"}, {"type": "standard", "ref": "CPCB"}, {"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('5a9e3e5b', 'Toxic metals and industrial pollution', 'gs-toxic-metals-and-industrial-pollution-9f2956be', '[{"type": "ncert", "ref": "Class 12 Biology — Environmental Issues"}, {"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('50c227c7', 'Persistent pollutants and their effects', 'gs-persistent-pollutants-and-their-effects-168d023e', '[{"type": "standard", "ref": "Stockholm Convention"}, {"type": "standard", "ref": "Shankar IAS"}]'::jsonb),
  ('4bb3306d', 'Plastic waste and microplastics', 'gs-plastic-waste-and-microplastics-121c2bf2', '[{"type": "ncert", "ref": "Class 12 Biology — Environmental Issues"}, {"type": "standard", "ref": "Plastic Waste Management Rules"}]'::jsonb),
  ('564b065b', 'Water pollution and its control', 'gs-water-pollution-and-its-control-9b75cb3e', '[{"type": "ncert", "ref": "Class 12 Biology — Environmental Issues"}, {"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('cb0b98ec', 'Solid wastes and e-waste', 'gs-solid-wastes-and-e-waste-0403f124', '[{"type": "ncert", "ref": "Class 12 Biology — Environmental Issues"}, {"type": "standard", "ref": "Waste Management Rules"}, {"type": "standard", "ref": "Shankar IAS"}]'::jsonb),
  ('9cb05e22', 'Agro-chemicals and their effects', 'gs-agro-chemicals-and-their-effects-2f648d4d', '[{"type": "ncert", "ref": "Class 12 Biology — Environmental Issues"}, {"type": "standard", "ref": "Shankar IAS Environment"}]'::jsonb),
  ('98ad1c9d', 'Greenhouse effect and global warming', 'gs-greenhouse-effect-and-global-warming-901862af', '[{"type": "ncert", "ref": "Class 12 Biology — Environmental Issues"}, {"type": "standard", "ref": "IPCC summaries"}, {"type": "standard", "ref": "Shankar IAS"}]'::jsonb),
  ('9b6155ff', 'Carbon sinks and sequestration', 'gs-carbon-sinks-and-sequestration-de8159f7', '[{"type": "standard", "ref": "Shankar IAS Environment"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('741b1b26', 'Carbon markets and climate metrics', 'gs-carbon-markets-and-climate-metrics-189acf09', '[{"type": "standard", "ref": "Economic Survey"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('69f5f696', 'Climate treaties, institutions and initiatives', 'gs-climate-treaties-institutions-and-initiatives-eb42d3a4', '[{"type": "standard", "ref": "Shankar IAS Environment"}, {"type": "standard", "ref": "UNFCCC"}]'::jsonb),
  ('9a41122b', 'Geoengineering', 'gs-geoengineering-b95f6e45', '[{"type": "standard", "ref": "Current affairs"}, {"type": "standard", "ref": "science journalism"}]'::jsonb),
  ('75ca9347', 'Renewable energy', 'gs-renewable-energy-9be0c591', '[{"type": "standard", "ref": "MNRE"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('db700d76', 'Alternative and cleaner fuels', 'gs-alternative-and-cleaner-fuels-e3552ab7', '[{"type": "standard", "ref": "PIB"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('1e6c07b8', 'Sustainable agriculture practices', 'gs-sustainable-agriculture-practices-c9f4fc5b', '[{"type": "ncert", "ref": "Class 11 Indian Economic Development"}, {"type": "standard", "ref": "ICAR"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('b75efc14', 'Philosophy of the Constitution', 'gs-philosophy-of-the-constitution-e1013404', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Philosophy of the Constitution"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('7110e9d8', 'Making of the Constitution', 'gs-making-of-the-constitution-358add37', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Constitution: Why and How?"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('0ebbb2b4', 'Parts and Schedules of the Constitution', 'gs-parts-and-schedules-of-the-constitution-5f068e73', '[{"type": "standard", "ref": "Laxmikanth"}, {"type": "standard", "ref": "Bare Act"}]'::jsonb),
  ('c84898db', 'Fundamental Rights', 'gs-fundamental-rights-d29a48dc', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Rights in the Indian Constitution"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('0ad674a9', 'Right to life and personal liberty', 'gs-right-to-life-and-personal-liberty-466f71d9', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Rights in the Indian Constitution"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('7125cf43', 'Right to Property', 'gs-right-to-property-cc0e3922', '[{"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('05a42bff', 'Directive Principles and Fundamental Duties', 'gs-directive-principles-and-fundamental-duties-39119d41', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('601b76a3', 'Writs and constitutional remedies', 'gs-writs-and-constitutional-remedies-b17aa82d', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — The Judiciary"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('758fb132', 'The President and the Union Executive', 'gs-the-president-and-the-union-executive-78e7c425', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Executive"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('89f9867d', 'Governor and the state executive', 'gs-governor-and-the-state-executive-d99f5fc3', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Executive"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('07d0f9f8', 'Prime Minister and Council of Ministers', 'gs-prime-minister-and-council-of-ministers-69a0e3ed', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Executive"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('21e5e3a1', 'Parliament: composition and procedure', 'gs-parliament-composition-and-procedure-546f6580', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Legislature"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('8c9499a4', 'Types of bills and the legislative process', 'gs-types-of-bills-and-the-legislative-process-6fc76b0c', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Legislature"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('c04bfe17', 'Parliamentary committees', 'gs-parliamentary-committees-ce9f360c', '[{"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('33a6cc51', 'Presiding officers, privileges and office of profit', 'gs-presiding-officers-privileges-and-office-of-profit-e814add7', '[{"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('ef19b179', 'Constitutional amendment procedure', 'gs-constitutional-amendment-procedure-c7a5301e', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Constitution as a Living Document"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('1dd4bd6f', 'Supreme Court: jurisdiction and composition', 'gs-supreme-court-jurisdiction-and-composition-2321748d', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — The Judiciary"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('6fa3309d', 'High Courts and subordinate judiciary', 'gs-high-courts-and-subordinate-judiciary-95cbff01', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — The Judiciary"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('63ae071a', 'Judicial review and basic structure', 'gs-judicial-review-and-basic-structure-b19c6b79', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Constitution as a Living Document"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('b0e9c565', 'Contempt of court and judicial accountability', 'gs-contempt-of-court-and-judicial-accountability-d8615c2e', '[{"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('6fe2005c', 'Legal profession and access to justice', 'gs-legal-profession-and-access-to-justice-ac87d9d7', '[{"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('7633e848', 'Centre-State relations', 'gs-centre-state-relations-61557f7c', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Federalism"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('180a9b2f', 'Emergency provisions', 'gs-emergency-provisions-65fcd969', '[{"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('347ca3d5', 'Federalism in India', 'gs-federalism-in-india-219d1618', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Federalism"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('520ffe2a', 'Special provisions for states and areas', 'gs-special-provisions-for-states-and-areas-75ac8ee9', '[{"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('fdc986d4', 'Local governments', 'gs-local-governments-168b173c', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Local Governments"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('1afc4357', 'Election and representation', 'gs-election-and-representation-6f3b6333', '[{"type": "ncert", "ref": "Class 11 Indian Constitution at Work — Election and Representation"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('7f08042b', 'Political parties and anti-defection', 'gs-political-parties-and-anti-defection-df7ce604', '[{"type": "ncert", "ref": "Class 12 Politics in India Since Independence"}, {"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('e4c262b4', 'Reservation of seats and representation', 'gs-reservation-of-seats-and-representation-7cf82c0c', '[{"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('3fcb6de8', 'Constitutional bodies', 'gs-constitutional-bodies-7f495907', '[{"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('66a6ed8a', 'Statutory and regulatory bodies', 'gs-statutory-and-regulatory-bodies-c3c6b241', '[{"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('796be476', 'Citizenship and domicile', 'gs-citizenship-and-domicile-674a26ca', '[{"type": "standard", "ref": "Laxmikanth"}]'::jsonb),
  ('4961002d', 'Governance, transparency and accountability', 'gs-governance-transparency-and-accountability-657f1a08', '[{"type": "standard", "ref": "2nd ARC reports"}]'::jsonb),
  ('e1a5612a', 'Internal security administration', 'gs-internal-security-administration-f38de4db', '[{"type": "standard", "ref": "MHA Annual Report"}]'::jsonb),
  ('03bdd74d', 'National symbols, honours and awards', 'gs-national-symbols-honours-and-awards-34dfee0d', '[{"type": "standard", "ref": "India Year Book"}]'::jsonb),
  ('b9e2268e', 'Interior of the earth', 'gs-interior-of-the-earth-ef2b4527', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography — Interior of the Earth"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('2f44b4db', 'Plate tectonics', 'gs-plate-tectonics-4cc4f3c5', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography — Distribution of Oceans and Continents"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('93e6b74b', 'Volcanism', 'gs-volcanism-44b29f87', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography — Interior of the Earth"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('9a055491', 'Geomorphic processes and landforms', 'gs-geomorphic-processes-and-landforms-407e979c', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography — Geomorphic Processes"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('523f626e', 'Minerals and rocks', 'gs-minerals-and-rocks-21ff49e2', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography — Minerals and Rocks"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('7556e6ac', 'Composition and structure of atmosphere', 'gs-composition-and-structure-of-atmosphere-a60a185d', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('6cfd3c3c', 'Solar radiation, heat balance and temperature', 'gs-solar-radiation-heat-balance-and-temperature-d4396e03', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('87041523', 'Atmospheric circulation and weather systems', 'gs-atmospheric-circulation-and-weather-systems-2b9d3de6', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('eaacf60f', 'Planetary winds and Coriolis effect', 'gs-planetary-winds-and-coriolis-effect-bc0aa319', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('b93c6ca1', 'Water in the atmosphere', 'gs-water-in-the-atmosphere-46dd48f6', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('aa8350fa', 'World climate and climate change', 'gs-world-climate-and-climate-change-bf6d914e', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('7f80d70d', 'Climate of India', 'gs-climate-of-india-89877da6', '[{"type": "ncert", "ref": "Class 11 India: Physical Environment — Climate"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('9d62b3a9', 'Movements of ocean water', 'gs-movements-of-ocean-water-35ec9a62', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('ace3fd37', 'Oceans: temperature and salinity', 'gs-oceans-temperature-and-salinity-064347d4', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography — Water (Oceans)"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('ac36747a', 'Seas, straits and maritime chokepoints', 'gs-seas-straits-and-maritime-chokepoints-55cf9800', '[{"type": "standard", "ref": "Oxford School Atlas"}]'::jsonb),
  ('0cabc0e9', 'Physiography of India', 'gs-physiography-of-india-7a313451', '[{"type": "ncert", "ref": "Class 11 India: Physical Environment — Physiography"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('ebe20275', 'Drainage system of India', 'gs-drainage-system-of-india-ec7bd8d7', '[{"type": "ncert", "ref": "Class 11 India: Physical Environment — Drainage System"}, {"type": "standard", "ref": "Oxford School Atlas"}]'::jsonb),
  ('e468d421', 'Lakes, waterfalls and inland water bodies', 'gs-lakes-waterfalls-and-inland-water-bodies-b7906796', '[{"type": "standard", "ref": "Oxford School Atlas"}]'::jsonb),
  ('8b0d90c2', 'Soils of India', 'gs-soils-of-india-bce54f06', '[{"type": "ncert", "ref": "Class 11 India: Physical Environment — Soils"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('9b419dbd', 'Natural vegetation', 'gs-natural-vegetation-7abfb068', '[{"type": "ncert", "ref": "Class 11 India: Physical Environment — Natural Vegetation"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('ca69ea82', 'Mineral and energy resources', 'gs-mineral-and-energy-resources-7d3f5bcf', '[{"type": "ncert", "ref": "Class 12 India: People and Economy — Mineral and Energy Resources"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('913b826e', 'Land resources and agriculture', 'gs-land-resources-and-agriculture-3b671893', '[{"type": "ncert", "ref": "Class 12 India: People and Economy — Land Resources and Agriculture"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('c8d9194d', 'Manufacturing industries', 'gs-manufacturing-industries-ff99d54d', '[{"type": "ncert", "ref": "Class 12 India: People and Economy — Manufacturing Industries"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('e3cf11b7', 'Transport and communication', 'gs-transport-and-communication-e37ba4c5', '[{"type": "ncert", "ref": "Class 12 India: People and Economy — Transport and Communication"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('5a8bc4f5', 'Ports and inland waterways', 'gs-ports-and-inland-waterways-9e41e316', '[{"type": "ncert", "ref": "Class 12 India: People and Economy — Transport and Communication"}, {"type": "standard", "ref": "Sagarmala"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('ef2163b5', 'World political geography and regions in news', 'gs-world-political-geography-and-regions-in-news-c254325a', '[{"type": "standard", "ref": "Oxford School Atlas"}, {"type": "standard", "ref": "newspapers"}]'::jsonb),
  ('6b2ca3a8', 'World physical features and landmarks', 'gs-world-physical-features-and-landmarks-5f4b69b3', '[{"type": "standard", "ref": "Oxford School Atlas"}]'::jsonb),
  ('84bc27b9', 'International boundaries and border disputes', 'gs-international-boundaries-and-border-disputes-503de7b8', '[{"type": "standard", "ref": "Oxford School Atlas"}, {"type": "standard", "ref": "MEA"}]'::jsonb),
  ('58c3f676', 'World agricultural and mineral producers', 'gs-world-agricultural-and-mineral-producers-c03a4c52', '[{"type": "standard", "ref": "Oxford School Atlas"}]'::jsonb),
  ('1d225731', 'Motions of the earth', 'gs-motions-of-the-earth-d31ca9e7', '[{"type": "ncert", "ref": "Class 11 Fundamentals of Physical Geography — The Earth"}, {"type": "standard", "ref": "GC Leong"}]'::jsonb),
  ('bd9085aa', 'Map work and remote sensing', 'gs-map-work-and-remote-sensing-88c24445', '[{"type": "ncert", "ref": "Class 11 Practical Work in Geography"}, {"type": "standard", "ref": "Oxford School Atlas"}]'::jsonb),
  ('512e8c00', 'Harappan civilisation', 'gs-harappan-civilisation-15d375b7', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History I — Bricks, Beads and Bones"}, {"type": "standard", "ref": "Old NCERT Ancient India (RS Sharma)"}]'::jsonb),
  ('4af21078', 'Vedic age', 'gs-vedic-age-b14422d4', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History I"}, {"type": "standard", "ref": "Old NCERT Ancient India (RS Sharma)"}]'::jsonb),
  ('5cd4d5a6', 'Buddhism', 'gs-buddhism-3db24767', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History I — Thinkers, Beliefs and Buildings"}, {"type": "standard", "ref": "Old NCERT Ancient India"}]'::jsonb),
  ('88219a6b', 'Jainism', 'gs-jainism-d4dfa3d4', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History I — Thinkers, Beliefs and Buildings"}, {"type": "standard", "ref": "Old NCERT Ancient India"}]'::jsonb),
  ('1cd9949b', 'Mauryan empire', 'gs-mauryan-empire-18548c07', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History I — Kings, Farmers and Towns"}, {"type": "standard", "ref": "Old NCERT Ancient India"}]'::jsonb),
  ('64bfe1f1', 'Post-Mauryan period and the Sangam age', 'gs-post-mauryan-period-and-the-sangam-age-7852ef91', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History I"}, {"type": "standard", "ref": "Old NCERT Ancient India"}]'::jsonb),
  ('93e92dcb', 'Gupta period', 'gs-gupta-period-2e24d92e', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History I"}, {"type": "standard", "ref": "Old NCERT Ancient India"}]'::jsonb),
  ('1722f5df', 'Ancient Indian literature and authors', 'gs-ancient-indian-literature-and-authors-ea4b5336', '[{"type": "standard", "ref": "Nitin Singhania Art and Culture"}]'::jsonb),
  ('9ef945d6', 'Early trade and urban centres', 'gs-early-trade-and-urban-centres-b403119f', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History I — Kings, Farmers and Towns"}, {"type": "standard", "ref": "Old NCERT Ancient India"}]'::jsonb),
  ('93929d93', 'Early medieval dynasties', 'gs-early-medieval-dynasties-82d042a3', '[{"type": "standard", "ref": "Old NCERT Medieval India (Satish Chandra)"}]'::jsonb),
  ('586d5666', 'Delhi Sultanate — administration and revenue', 'gs-delhi-sultanate-administration-and-revenue-62c8d95f', '[{"type": "standard", "ref": "Old NCERT Medieval India (Satish Chandra)"}]'::jsonb),
  ('f75261c6', 'Delhi Sultanate — rulers and campaigns', 'gs-delhi-sultanate-rulers-and-campaigns-d469bfd6', '[{"type": "standard", "ref": "Old NCERT Medieval India (Satish Chandra)"}]'::jsonb),
  ('4d279345', 'Vijayanagara empire', 'gs-vijayanagara-empire-68856475', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History II — An Imperial Capital: Vijayanagara"}, {"type": "standard", "ref": "Old NCERT Medieval India"}]'::jsonb),
  ('a1896442', 'Mughal administration and land revenue', 'gs-mughal-administration-and-land-revenue-0839f9b7', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History II — Peasants, Zamindars and the State"}, {"type": "standard", "ref": "Old NCERT Medieval India"}]'::jsonb),
  ('cb50b194', 'Mughal empire — rulers and succession', 'gs-mughal-empire-rulers-and-succession-6e560b9b', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History II — Kings and Chronicles"}, {"type": "standard", "ref": "Old NCERT Medieval India"}]'::jsonb),
  ('11f635d2', 'Bhakti movement', 'gs-bhakti-movement-cca2792d', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History II — Bhakti-Sufi Traditions"}, {"type": "standard", "ref": "Nitin Singhania Art and Culture"}]'::jsonb),
  ('37160da9', 'Sufi traditions', 'gs-sufi-traditions-755c0225', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History II — Bhakti-Sufi Traditions"}, {"type": "standard", "ref": "Nitin Singhania Art and Culture"}]'::jsonb),
  ('bb64c318', 'Regional kingdoms and the Marathas', 'gs-regional-kingdoms-and-the-marathas-e9918b56', '[{"type": "standard", "ref": "Old NCERT Medieval India"}]'::jsonb),
  ('be28bc4d', 'European arrival and trading companies', 'gs-european-arrival-and-trading-companies-6aeaf09f', '[{"type": "standard", "ref": "Spectrum Modern India"}]'::jsonb),
  ('8b8d195d', 'Temple architecture', 'gs-temple-architecture-d76721e4', '[{"type": "ncert", "ref": "Class 11 An Introduction to Indian Art"}, {"type": "standard", "ref": "Nitin Singhania Art and Culture"}]'::jsonb),
  ('ae7b07ac', 'Buddhist and Jain rock-cut architecture', 'gs-buddhist-and-jain-rock-cut-architecture-bcd7c44f', '[{"type": "ncert", "ref": "Class 11 An Introduction to Indian Art"}, {"type": "standard", "ref": "Nitin Singhania Art and Culture"}]'::jsonb),
  ('cbb792cd', 'Indo-Islamic architecture', 'gs-indo-islamic-architecture-a8e751fd', '[{"type": "ncert", "ref": "Class 11 An Introduction to Indian Art"}, {"type": "standard", "ref": "Nitin Singhania Art and Culture"}]'::jsonb),
  ('4ff96891', 'Painting traditions and schools', 'gs-painting-traditions-and-schools-9650b87b', '[{"type": "ncert", "ref": "Class 11 An Introduction to Indian Art"}, {"type": "standard", "ref": "Nitin Singhania Art and Culture"}]'::jsonb),
  ('31f1d931', 'Classical and folk dance', 'gs-classical-and-folk-dance-d1a42982', '[{"type": "standard", "ref": "CCRT"}, {"type": "standard", "ref": "Nitin Singhania Art and Culture"}]'::jsonb),
  ('a4b0c3b7', 'Music traditions and composers', 'gs-music-traditions-and-composers-e09b00b5', '[{"type": "standard", "ref": "CCRT"}, {"type": "standard", "ref": "Nitin Singhania Art and Culture"}]'::jsonb),
  ('66802b7b', 'Crafts, textiles and geographical indications', 'gs-crafts-textiles-and-geographical-indications-a5e8d37e', '[{"type": "standard", "ref": "CCRT"}, {"type": "standard", "ref": "GI Registry"}]'::jsonb),
  ('2ccca1e9', 'Festivals and regional traditions', 'gs-festivals-and-regional-traditions-636996de', '[{"type": "standard", "ref": "CCRT"}]'::jsonb),
  ('6be63a96', 'UNESCO heritage listings', 'gs-unesco-heritage-listings-52c0e51e', '[{"type": "standard", "ref": "UNESCO India list"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('daa689f2', 'East India Company expansion and subsidiary alliance', 'gs-east-india-company-expansion-and-subsidiary-alliance-6313e801', '[{"type": "standard", "ref": "Spectrum Modern India"}]'::jsonb),
  ('1f90fbbf', 'Colonial land revenue systems', 'gs-colonial-land-revenue-systems-5d496955', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History III — Colonialism and the Countryside"}, {"type": "standard", "ref": "Spectrum Modern India"}]'::jsonb),
  ('31cf0e35', 'Colonial education and social reform', 'gs-colonial-education-and-social-reform-15a6f7a4', '[{"type": "standard", "ref": "Spectrum Modern India"}]'::jsonb),
  ('3e240607', 'Early nationalism and the moderate phase', 'gs-early-nationalism-and-the-moderate-phase-60e297fc', '[{"type": "standard", "ref": "Spectrum Modern India"}]'::jsonb),
  ('971a22b9', 'Revolutionary movements and armed struggle', 'gs-revolutionary-movements-and-armed-struggle-751a847d', '[{"type": "standard", "ref": "Spectrum Modern India"}]'::jsonb),
  ('29af2935', 'Gandhian mass movements', 'gs-gandhian-mass-movements-44a9767c', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History III — Mahatma Gandhi and the Nationalist Movement"}, {"type": "standard", "ref": "Spectrum Modern India"}]'::jsonb),
  ('69b0ea72', 'Peasant, tribal and labour movements', 'gs-peasant-tribal-and-labour-movements-a7073f43', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History III — Rebels and the Raj"}, {"type": "standard", "ref": "Spectrum Modern India"}]'::jsonb),
  ('8c060e1c', 'Constitutional reforms and Government of India Acts', 'gs-constitutional-reforms-and-government-of-india-acts-b11f1496', '[{"type": "standard", "ref": "Spectrum Modern India"}]'::jsonb),
  ('8713e217', 'Partition, integration and independence', 'gs-partition-integration-and-independence-b8b7146d', '[{"type": "ncert", "ref": "Class 12 Themes in Indian History III — Understanding Partition"}, {"type": "standard", "ref": "Spectrum Modern India"}]'::jsonb),
  ('2192efc2', 'National income and its aggregates', 'gs-national-income-and-its-aggregates-1f736aa4', '[{"type": "ncert", "ref": "Class 12 Introductory Macroeconomics — National Income Accounting"}, {"type": "standard", "ref": "Ramesh Singh"}]'::jsonb),
  ('7889a551', 'Economic growth and development indicators', 'gs-economic-growth-and-development-indicators-74d5e715', '[{"type": "ncert", "ref": "Class 11 Indian Economic Development"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('2707150a', 'Demand, supply and market equilibrium', 'gs-demand-supply-and-market-equilibrium-6421e4c0', '[{"type": "ncert", "ref": "Class 12 Introductory Microeconomics"}, {"type": "standard", "ref": "Ramesh Singh"}]'::jsonb),
  ('10e4c33b', 'Inflation — types and measurement', 'gs-inflation-types-and-measurement-2d1cf1cd', '[{"type": "ncert", "ref": "Class 12 Introductory Macroeconomics"}, {"type": "standard", "ref": "Ramesh Singh"}]'::jsonb),
  ('a8939b7e', 'Capital formation and human capital', 'gs-capital-formation-and-human-capital-a7465fc4', '[{"type": "ncert", "ref": "Class 11 Indian Economic Development — Human Capital Formation"}, {"type": "standard", "ref": "Ramesh Singh"}]'::jsonb),
  ('3ea83231', 'Poverty and its estimation', 'gs-poverty-and-its-estimation-3c8a4adb', '[{"type": "ncert", "ref": "Class 11 Indian Economic Development — Poverty"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('8f635c62', 'Employment: growth and informalisation', 'gs-employment-growth-and-informalisation-ac4b2580', '[{"type": "ncert", "ref": "Class 11 Indian Economic Development — Employment"}, {"type": "standard", "ref": "Economic Survey"}, {"type": "standard", "ref": "PLFS"}]'::jsonb),
  ('f5ad1028', 'Money and banking: RBI and monetary policy', 'gs-money-and-banking-rbi-and-monetary-policy-a967d6a0', '[{"type": "ncert", "ref": "Class 12 Introductory Macroeconomics — Money and Banking"}, {"type": "standard", "ref": "Ramesh Singh"}]'::jsonb),
  ('5767d76c', 'Money supply and the multiplier', 'gs-money-supply-and-the-multiplier-95bbc6d6', '[{"type": "ncert", "ref": "Class 12 Introductory Macroeconomics — Money and Banking"}, {"type": "standard", "ref": "Ramesh Singh"}]'::jsonb),
  ('3860384c', 'Liquidity instruments and open market operations', 'gs-liquidity-instruments-and-open-market-operations-ca88958f', '[{"type": "standard", "ref": "RBI website"}, {"type": "standard", "ref": "Ramesh Singh"}]'::jsonb),
  ('4ae1a175', 'Commercial banking and asset classification', 'gs-commercial-banking-and-asset-classification-f0ff4ba2', '[{"type": "standard", "ref": "RBI Financial Stability Report"}]'::jsonb),
  ('3d5f609a', 'Public sector banks and governance', 'gs-public-sector-banks-and-governance-5059b3b9', '[{"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('071d0c52', 'Cooperative banks and regional rural banks', 'gs-cooperative-banks-and-regional-rural-banks-f80698ac', '[{"type": "standard", "ref": "RBI website"}]'::jsonb),
  ('624b9c56', 'Non-banking financial companies', 'gs-non-banking-financial-companies-e66dedc0', '[{"type": "standard", "ref": "RBI website"}]'::jsonb),
  ('9b05314d', 'Financial inclusion and microfinance', 'gs-financial-inclusion-and-microfinance-fef69c9d', '[{"type": "standard", "ref": "Economic Survey"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('f21ab90d', 'Digital payments and payment systems', 'gs-digital-payments-and-payment-systems-6f6f52ce', '[{"type": "standard", "ref": "NPCI"}, {"type": "standard", "ref": "RBI"}]'::jsonb),
  ('3b0a64fd', 'Central bank digital currency', 'gs-central-bank-digital-currency-fe40b1a0', '[{"type": "standard", "ref": "RBI concept note"}]'::jsonb),
  ('26c18d07', 'Money market instruments', 'gs-money-market-instruments-f08ff148', '[{"type": "standard", "ref": "RBI website"}, {"type": "standard", "ref": "Ramesh Singh"}]'::jsonb),
  ('64bfd004', 'Capital market instruments and bonds', 'gs-capital-market-instruments-and-bonds-1b709979', '[{"type": "standard", "ref": "SEBI"}, {"type": "standard", "ref": "Ramesh Singh"}]'::jsonb),
  ('598d7ce8', 'Equity markets and market participants', 'gs-equity-markets-and-market-participants-0266d08b', '[{"type": "standard", "ref": "SEBI"}]'::jsonb),
  ('c06dd0e0', 'Mutual funds, ETFs and investment trusts', 'gs-mutual-funds-etfs-and-investment-trusts-a4d95c78', '[{"type": "standard", "ref": "SEBI"}]'::jsonb),
  ('2c510a52', 'Credit rating agencies', 'gs-credit-rating-agencies-1a595538', '[{"type": "standard", "ref": "SEBI"}]'::jsonb),
  ('8f03c3e9', 'Financial regulation and investor protection', 'gs-financial-regulation-and-investor-protection-ed247358', '[{"type": "standard", "ref": "SEBI"}, {"type": "standard", "ref": "RBI"}]'::jsonb),
  ('b2f1e8ea', 'Union Budget and the budget process', 'gs-union-budget-and-the-budget-process-fdab47cf', '[{"type": "ncert", "ref": "Class 12 Introductory Macroeconomics — Government Budget and the Economy"}, {"type": "standard", "ref": "Ramesh Singh"}]'::jsonb),
  ('0e80d2a1', 'Taxation — direct and indirect', 'gs-taxation-direct-and-indirect-353e99fa', '[{"type": "ncert", "ref": "Class 12 Introductory Macroeconomics — Government Budget and the Economy"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('61120bdd', 'Finance Commission and tax devolution', 'gs-finance-commission-and-tax-devolution-8fca86cf', '[{"type": "standard", "ref": "Finance Commission report"}]'::jsonb),
  ('9f62ad97', 'Fiscal deficit and FRBM', 'gs-fiscal-deficit-and-frbm-051799b2', '[{"type": "ncert", "ref": "Class 12 Introductory Macroeconomics"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('48f9772e', 'Government borrowing and public debt', 'gs-government-borrowing-and-public-debt-cc23f4bf', '[{"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('71716840', 'Balance of payments', 'gs-balance-of-payments-1eda4821', '[{"type": "ncert", "ref": "Class 12 Introductory Macroeconomics — Open Economy Macroeconomics"}, {"type": "standard", "ref": "Ramesh Singh"}]'::jsonb),
  ('d6152647', 'Foreign exchange rate', 'gs-foreign-exchange-rate-eafb2a70', '[{"type": "ncert", "ref": "Class 12 Introductory Macroeconomics — Open Economy Macroeconomics"}, {"type": "standard", "ref": "Ramesh Singh"}]'::jsonb),
  ('77b2c28a', 'Foreign investment — FDI and FPI', 'gs-foreign-investment-fdi-and-fpi-9dda61e7', '[{"type": "standard", "ref": "Economic Survey"}, {"type": "standard", "ref": "DPIIT"}]'::jsonb),
  ('9831ee26', 'External debt and sovereign borrowing', 'gs-external-debt-and-sovereign-borrowing-bcfeb781', '[{"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('803e588e', 'International trade and WTO', 'gs-international-trade-and-wto-addf5616', '[{"type": "ncert", "ref": "Class 11 Indian Economic Development"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('faae405c', 'International economic institutions', 'gs-international-economic-institutions-f81f89a6', '[{"type": "standard", "ref": "Economic Survey"}, {"type": "standard", "ref": "IMF/World Bank"}]'::jsonb),
  ('8e834bd5', 'Agricultural marketing, MSP and procurement', 'gs-agricultural-marketing-msp-and-procurement-ce7225ea', '[{"type": "ncert", "ref": "Class 11 Indian Economic Development — Rural Development"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('ee473b0f', 'Food security and public distribution', 'gs-food-security-and-public-distribution-bd25b759', '[{"type": "ncert", "ref": "Class 11 Indian Economic Development — Rural Development"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('e50a7e81', 'Industrial policy and MSMEs', 'gs-industrial-policy-and-msmes-10172954', '[{"type": "ncert", "ref": "Class 11 Indian Economic Development — Liberalisation"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('cb6b1afa', 'Services sector and e-commerce', 'gs-services-sector-and-e-commerce-8b889401', '[{"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('3c34cf1b', 'Infrastructure and public-private partnership', 'gs-infrastructure-and-public-private-partnership-b55df595', '[{"type": "ncert", "ref": "Class 11 Indian Economic Development — Infrastructure"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('61e36414', 'Energy and mineral sector economics', 'gs-energy-and-mineral-sector-economics-4f1fc8f6', '[{"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('07148e1a', 'Health system and public health programmes', 'gs-health-system-and-public-health-programmes-c8c4288a', '[{"type": "ncert", "ref": "Class 11 Indian Economic Development — Human Capital Formation"}, {"type": "standard", "ref": "Economic Survey"}, {"type": "standard", "ref": "NFHS"}]'::jsonb),
  ('228a5283', 'Education policy and skill development', 'gs-education-policy-and-skill-development-8e6d1fc0', '[{"type": "ncert", "ref": "Class 11 Indian Economic Development — Human Capital Formation"}, {"type": "standard", "ref": "Economic Survey"}, {"type": "standard", "ref": "NEP 2020"}]'::jsonb),
  ('15624d65', 'Nutrition and food safety', 'gs-nutrition-and-food-safety-a1c22819', '[{"type": "standard", "ref": "FSSAI"}, {"type": "standard", "ref": "NFHS"}]'::jsonb),
  ('d824c6e9', 'Population and demography', 'gs-population-and-demography-49387895', '[{"type": "ncert", "ref": "Class 12 Fundamentals of Human Geography — Population"}, {"type": "standard", "ref": "Census"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('5d61a8fd', 'Social security, pensions and labour welfare', 'gs-social-security-pensions-and-labour-welfare-99935fe1', '[{"type": "standard", "ref": "Labour Codes"}, {"type": "standard", "ref": "Economic Survey"}]'::jsonb),
  ('74a4adff', 'Tribal and vulnerable group welfare', 'gs-tribal-and-vulnerable-group-welfare-3ef388d9', '[{"type": "standard", "ref": "Ministry of Tribal Affairs"}, {"type": "standard", "ref": "India Year Book"}]'::jsonb),
  ('cea3c9c5', 'Cell structure and human physiology', 'gs-cell-structure-and-human-physiology-ad49d0f8', '[{"type": "ncert", "ref": "Class 11 Biology — Cell: The Unit of Life; Human Physiology"}]'::jsonb),
  ('a218d1ba', 'Molecular basis of inheritance', 'gs-molecular-basis-of-inheritance-9fd98406', '[{"type": "ncert", "ref": "Class 12 Biology — Molecular Basis of Inheritance"}]'::jsonb),
  ('a4d2c72a', 'Immunity and vaccines', 'gs-immunity-and-vaccines-dfacfc20', '[{"type": "ncert", "ref": "Class 12 Biology — Human Health and Disease"}]'::jsonb),
  ('59a26ffc', 'Microbes and biological classification', 'gs-microbes-and-biological-classification-bef8073b', '[{"type": "ncert", "ref": "Class 11 Biology — Biological Classification; Class 12 — Microbes in Human Welfare"}]'::jsonb),
  ('cc133a7d', 'Human health and disease', 'gs-human-health-and-disease-9d6a73cf', '[{"type": "ncert", "ref": "Class 12 Biology — Human Health and Disease"}, {"type": "standard", "ref": "Current affairs"}]'::jsonb),
  ('5b00d743', 'Motion, force and thermodynamics', 'gs-motion-force-and-thermodynamics-975acfd8', '[{"type": "ncert", "ref": "Class 11 Physics"}]'::jsonb),
  ('f04a60bb', 'Waves, sound and optics', 'gs-waves-sound-and-optics-36e71fc8', '[{"type": "ncert", "ref": "Class 11–12 Physics"}]'::jsonb),
  ('a7c38826', 'Electricity and magnetism', 'gs-electricity-and-magnetism-d213c0bb', '[{"type": "ncert", "ref": "Class 12 Physics"}]'::jsonb),
  ('4971ff36', 'Atoms and nuclei', 'gs-atoms-and-nuclei-b231d58a', '[{"type": "ncert", "ref": "Class 12 Physics — Atoms; Nuclei"}]'::jsonb),
  ('47dcedf5', 'States of matter and material properties', 'gs-states-of-matter-and-material-properties-db188d06', '[{"type": "ncert", "ref": "Class 11 Chemistry"}]'::jsonb),
  ('39f1a761', 'Chemistry in everyday life', 'gs-chemistry-in-everyday-life-90dca2b8', '[{"type": "ncert", "ref": "Class 12 Chemistry — Chemistry in Everyday Life"}]'::jsonb),
  ('21c46069', 'Biotechnology and its applications', 'gs-biotechnology-and-its-applications-f56d5dfd', '[{"type": "ncert", "ref": "Class 12 Biology — Biotechnology and its Applications"}, {"type": "standard", "ref": "PIB"}, {"type": "standard", "ref": "current affairs"}]'::jsonb),
  ('bd5847e7', 'Disease vectors and public health interventions', 'gs-disease-vectors-and-public-health-interventions-fd0baa43', '[{"type": "ncert", "ref": "Class 12 Biology — Human Health and Disease"}, {"type": "standard", "ref": "PIB"}, {"type": "standard", "ref": "WHO"}]'::jsonb),
  ('e57ad5b3', 'Space technology and launch vehicles', 'gs-space-technology-and-launch-vehicles-bd3affd2', '[{"type": "standard", "ref": "ISRO website"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('ede5a5e1', 'Satellites and navigation', 'gs-satellites-and-navigation-df518d8b', '[{"type": "standard", "ref": "ISRO website"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('15936c3d', 'Space missions', 'gs-space-missions-ad6231e1', '[{"type": "standard", "ref": "ISRO website"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('2f1b7047', 'Space science', 'gs-space-science-9a5052bc', '[{"type": "standard", "ref": "ISRO"}, {"type": "standard", "ref": "science journalism"}]'::jsonb),
  ('5858c30e', 'Artificial intelligence and machine learning', 'gs-artificial-intelligence-and-machine-learning-a3863058', '[{"type": "standard", "ref": "MeitY"}, {"type": "standard", "ref": "current affairs"}]'::jsonb),
  ('e2e8bf83', 'Blockchain, cryptocurrency and Web3', 'gs-blockchain-cryptocurrency-and-web3-6d6a34e2', '[{"type": "standard", "ref": "RBI"}, {"type": "standard", "ref": "MeitY"}]'::jsonb),
  ('9ae14a1c', 'Cybersecurity and cyber threats', 'gs-cybersecurity-and-cyber-threats-a4370034', '[{"type": "standard", "ref": "CERT-In"}, {"type": "standard", "ref": "MeitY"}]'::jsonb),
  ('e5a97b06', 'Data protection and digital governance', 'gs-data-protection-and-digital-governance-b090f814', '[{"type": "standard", "ref": "DPDP Act"}, {"type": "standard", "ref": "MeitY"}]'::jsonb),
  ('3e99163e', 'Telecom and networks', 'gs-telecom-and-networks-bcab1e75', '[{"type": "standard", "ref": "TRAI"}, {"type": "standard", "ref": "DoT"}]'::jsonb),
  ('ae80b3ab', 'Emerging technologies', 'gs-emerging-technologies-06244a4f', '[{"type": "standard", "ref": "MeitY"}, {"type": "standard", "ref": "science journalism"}]'::jsonb),
  ('814ac6fd', 'Nanotechnology', 'gs-nanotechnology-3aa01c5e', '[{"type": "standard", "ref": "DST"}, {"type": "standard", "ref": "science journalism"}]'::jsonb),
  ('692609bc', 'Nuclear energy technology', 'gs-nuclear-energy-technology-afcf3ec3', '[{"type": "ncert", "ref": "Class 12 Physics — Nuclei"}, {"type": "standard", "ref": "DAE"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('1abf068e', 'Batteries and energy storage', 'gs-batteries-and-energy-storage-3d58fdfb', '[{"type": "standard", "ref": "MNRE"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('de8ab3b1', 'Hydrogen and fuel cells', 'gs-hydrogen-and-fuel-cells-62781107', '[{"type": "standard", "ref": "National Hydrogen Mission"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('fca7b5dd', 'Armed forces structure and ranks', 'gs-armed-forces-structure-and-ranks-7e0a9be1', '[{"type": "standard", "ref": "MoD Annual Report"}]'::jsonb),
  ('cd941d98', 'Defence hardware and platforms', 'gs-defence-hardware-and-platforms-ff49515b', '[{"type": "standard", "ref": "MoD Annual Report"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('47eba1b6', 'Missile systems and strategic weapons', 'gs-missile-systems-and-strategic-weapons-7b518c41', '[{"type": "standard", "ref": "DRDO"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('40bf511c', 'Joint exercises and defence cooperation', 'gs-joint-exercises-and-defence-cooperation-e4546def', '[{"type": "standard", "ref": "MoD"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('5849c447', 'Internal security forces and paramilitary', 'gs-internal-security-forces-and-paramilitary-283f9795', '[{"type": "standard", "ref": "MHA Annual Report"}]'::jsonb),
  ('bac98697', 'Relations with neighbouring countries', 'gs-relations-with-neighbouring-countries-d4f92a16', '[{"type": "ncert", "ref": "Class 12 Contemporary World Politics"}, {"type": "standard", "ref": "MEA"}, {"type": "standard", "ref": "newspapers"}]'::jsonb),
  ('ffb14933', 'India and major powers', 'gs-india-and-major-powers-67279cd5', '[{"type": "ncert", "ref": "Class 12 Contemporary World Politics"}, {"type": "standard", "ref": "MEA"}, {"type": "standard", "ref": "newspapers"}]'::jsonb),
  ('6c1b6671', 'Connectivity and development partnerships', 'gs-connectivity-and-development-partnerships-d5acc349', '[{"type": "standard", "ref": "MEA"}, {"type": "standard", "ref": "newspapers"}]'::jsonb),
  ('49b4790b', 'Diaspora, consular and migration policy', 'gs-diaspora-consular-and-migration-policy-2d43ce3a', '[{"type": "standard", "ref": "MEA"}]'::jsonb),
  ('a6999dcd', 'Conflict zones and civil wars', 'gs-conflict-zones-and-civil-wars-21971ee0', '[{"type": "ncert", "ref": "Class 12 Contemporary World Politics"}, {"type": "standard", "ref": "Newspapers"}, {"type": "standard", "ref": "atlas"}]'::jsonb),
  ('f732797f', 'Territorial and maritime disputes', 'gs-territorial-and-maritime-disputes-719e0f21', '[{"type": "ncert", "ref": "Class 12 Contemporary World Politics"}, {"type": "standard", "ref": "Newspapers"}, {"type": "standard", "ref": "atlas"}]'::jsonb),
  ('ee6c5c2b', 'Political instability, coups and transitions', 'gs-political-instability-coups-and-transitions-04730229', '[{"type": "standard", "ref": "Newspapers"}]'::jsonb),
  ('f087e4aa', 'Refugee and humanitarian crises', 'gs-refugee-and-humanitarian-crises-d81eee37', '[{"type": "standard", "ref": "UNHCR"}, {"type": "standard", "ref": "newspapers"}]'::jsonb),
  ('93bda482', 'Country situations in news', 'gs-country-situations-in-news-b9fbbe52', '[{"type": "standard", "ref": "Newspapers"}]'::jsonb),
  ('f87ee241', 'United Nations system and principal organs', 'gs-united-nations-system-and-principal-organs-cfef7de8', '[{"type": "ncert", "ref": "Class 12 Contemporary World Politics — International Organisations"}, {"type": "standard", "ref": "UN website"}]'::jsonb),
  ('fa11b813', 'UN conventions and international law', 'gs-un-conventions-and-international-law-92a7412a', '[{"type": "standard", "ref": "UN website"}]'::jsonb),
  ('1af4be87', 'Regional groupings and economic blocs', 'gs-regional-groupings-and-economic-blocs-82bc8563', '[{"type": "ncert", "ref": "Class 12 Contemporary World Politics"}, {"type": "standard", "ref": "MEA"}]'::jsonb),
  ('bbf61f1e', 'Plurilateral and strategic groupings', 'gs-plurilateral-and-strategic-groupings-f8e54bb1', '[{"type": "standard", "ref": "MEA"}, {"type": "standard", "ref": "newspapers"}]'::jsonb),
  ('edb85caf', 'Export control and non-proliferation regimes', 'gs-export-control-and-non-proliferation-regimes-9ffaca6d', '[{"type": "standard", "ref": "MEA"}, {"type": "standard", "ref": "IAEA"}]'::jsonb),
  ('cebc029d', 'International indices and rankings', 'gs-international-indices-and-rankings-bca04ab1', '[{"type": "standard", "ref": "PIB"}, {"type": "standard", "ref": "index publishers"}]'::jsonb),
  ('9287d12d', 'Global summits, declarations and compacts', 'gs-global-summits-declarations-and-compacts-aaaa7343', '[{"type": "standard", "ref": "MEA"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('e336caf3', 'International maritime and polar governance', 'gs-international-maritime-and-polar-governance-fba06b8b', '[{"type": "standard", "ref": "UNCLOS"}, {"type": "standard", "ref": "MEA"}]'::jsonb),
  ('b56a807c', 'Awards, honours and civilian decorations', 'gs-awards-honours-and-civilian-decorations-43bad78c', '[{"type": "standard", "ref": "India Year Book"}, {"type": "standard", "ref": "PIB"}]'::jsonb),
  ('69cb3017', 'Sporting events and championships', 'gs-sporting-events-and-championships-2cafcea7', '[{"type": "standard", "ref": "Newspapers"}]'::jsonb),
  ('2d384e36', 'Books, authors and personalities in news', 'gs-books-authors-and-personalities-in-news-daed605d', '[{"type": "standard", "ref": "Newspapers"}]'::jsonb),
  ('ca4c910c', 'Days, observances and commemorations', 'gs-days-observances-and-commemorations-0aa1e1ad', '[{"type": "standard", "ref": "PIB"}]'::jsonb)
) AS v(prefix, name, slug, sources)
WHERE t.id::text LIKE v.prefix || '%' AND t.level = 'microtopic';

-- Deactivated: duplicate or merged elsewhere.
-- Internet of things and sensor technologies -> MERGE into Emerging technologies
UPDATE public.topics SET is_active = false
WHERE id::text LIKE '87385709' || '%';

COMMIT;
