import React, { useCallback, useEffect, useState } from "react";
import { useExamWorkspace } from "../ExamWorkspaceContext";
import { api } from "../../../../lib/api";

function ExtractionBadge({ status }) {
  const map = {
    succeeded:  { cls: "badge resolved", text: "extracted" },
    processing: { cls: "badge pending",  text: "extracting…" },
    pending:    { cls: "badge pending",  text: "queued" },
    failed:     { cls: "badge blocker",  text: "failed" },
  };
  const b = map[status] || { cls: "badge neutral", text: status ?? "—" };
  return <span className={b.cls}>{b.text}</span>;
}

const CMS = "/api/admin/exam-intelligence-cms";

export default function DocumentsPanel({ onGotoTab }) {
  const { exam, cycle } = useExamWorkspace();
  const [docs, setDocs] = useState([]);
  const [papers, setPapers] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    if (!exam?.id) return;
    setLoading(true);
    setError("");
    try {
      const qs = new URLSearchParams({ exam_id: exam.id, limit: "100" });
      if (cycle?.id) qs.set("cycle_id", cycle.id);
      const [sylResult, pyqResult] = await Promise.all([
        api.get(`${CMS}/syllabus-documents?${qs}`),
        api.get(`${CMS}/pyq-papers?${qs}`),
      ]);
      setDocs(sylResult?.items || sylResult || []);
      setPapers(pyqResult?.items || pyqResult || []);
    } catch (e) {
      setError(e?.message || "Failed to load documents");
    } finally {
      setLoading(false);
    }
  }, [exam?.id, cycle?.id]);

  useEffect(() => { load(); }, [load]);

  const allDocs = [
    ...docs.map((d) => ({ ...d, _kind: "syllabus" })),
    ...papers.map((p) => ({ ...p, _kind: "pyq" })),
  ];

  if (loading) {
    return (
      <div className="stack">
        <div className="scrn-head">
          <div className="scrn-tag">Always open · source documents</div>
          <h2 className="oc-title disp" style={{ fontSize: 20, marginTop: 3 }}>Documents</h2>
        </div>
        <div className="card">
          <div className="card-body">
            <div className="skel" style={{ height: 20, marginBottom: 10 }} />
            <div className="skel" style={{ height: 20, marginBottom: 10 }} />
            <div className="skel" style={{ height: 20 }} />
          </div>
        </div>
      </div>
    );
  }

  if (allDocs.length === 0) {
    return (
      <div className="stack">
        <div className="scrn-head">
          <div className="scrn-tag">Always open · source documents</div>
          <h2 className="oc-title disp" style={{ fontSize: 20, marginTop: 3 }}>Documents</h2>
        </div>
        {error && <div className="err-row">{error}</div>}
        <div className="card" style={{ borderStyle: "dashed" }}>
          <div className="empty" style={{ padding: "34px 18px" }}>
            <div className="empty-title">No documents yet</div>
            <div style={{ maxWidth: 440, margin: "0 auto 14px" }}>
              Upload the official syllabus or a PYQ paper PDF in the Exam CMS. Every mapping and
              question review starts from a verified document — nothing is generated by AI.
            </div>
          </div>
        </div>
      </div>
    );
  }

  const hasProcessing = allDocs.some(
    (d) => d.extraction_status === "processing" || d.extraction_status === "pending",
  );

  return (
    <div className="stack">
      <div className="scrn-head">
        <div>
          <div className="scrn-tag">Always open · source documents</div>
          <h2 className="oc-title disp" style={{ fontSize: 20, marginTop: 3 }}>
            Documents &amp; extraction
          </h2>
        </div>
        <div className="row" style={{ justifyContent: "flex-end" }}>
          <button className="btn small" onClick={load}>Refresh</button>
        </div>
      </div>

      {error && <div className="err-row">{error}</div>}

      <div className="card">
        <table className="t">
          <thead>
            <tr>
              <th>Document</th>
              <th>Kind</th>
              <th>Pages</th>
              <th>Extraction</th>
              <th>Added</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {allDocs.map((d) => {
              const name =
                d.document_name ?? d.file_name ?? d.label ??
                [d.year, d.paper_code, d.shift].filter(Boolean).join(" · ") ?? d.id;
              const pages = d.page_count ?? d.pages ?? "—";
              const extraction = d.extraction_status ?? d.extraction ?? null;
              const added = d.created_at
                ? new Date(d.created_at).toLocaleDateString("en-IN", {
                    day: "numeric", month: "short", year: "numeric",
                  })
                : "—";
              return (
                <tr key={d.id}>
                  <td>
                    <div className="row-ttl">{name}</div>
                    {d.source_url && (
                      <div className="row-sub" style={{ wordBreak: "break-all" }}>
                        {d.source_url}
                      </div>
                    )}
                  </td>
                  <td>
                    <span className="badge neutral no-dot">{d._kind}</span>
                  </td>
                  <td className="num">{pages}</td>
                  <td>
                    {extraction
                      ? <ExtractionBadge status={extraction} />
                      : <span className="badge neutral no-dot">—</span>}
                  </td>
                  <td className="num" style={{ color: "var(--ink-mute)" }}>{added}</td>
                  <td style={{ textAlign: "right" }}>
                    {d._kind === "syllabus" && (
                      <button
                        className="btn small"
                        onClick={() => onGotoTab && onGotoTab("syllabus")}
                      >
                        Map →
                      </button>
                    )}
                    {d._kind === "pyq" && (
                      <button
                        className="btn small"
                        onClick={() => onGotoTab && onGotoTab("pyq")}
                      >
                        Review →
                      </button>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {hasProcessing && (
        <div className="warn-row">
          One or more documents are still extracting — mappings stay unavailable until extraction
          succeeds.
        </div>
      )}
    </div>
  );
}
