-- 231_mock_practice_blueprint_source.sql
-- PYQ v2 PR-5/6 (slice B): learner PYQ practice reuses the generated-attempt
-- blueprint path (migrations 174/175/178/179) to assemble an ad-hoc attempt over
-- projected PYQ questions — no new attempt schema, no new route, and the existing
-- answer/submit/result/review flow is reused unchanged.
--
-- The only schema change practice needs is admitting its blueprint sources into
-- mock_generated_blueprints.source, which migration 174 CHECK-constrained to
-- ('exam_realistic','personalized'). Extend that CHECK to also allow the three
-- practice modes. Additive and backward-compatible: existing rows and the two
-- prior values remain valid.
--
-- The constraint carries the default inline name generated by migration 174
-- (<table>_<column>_check). Drop-if-exists then re-add so this is idempotent and
-- safe to re-run.
--
-- No RLS change: mock_generated_blueprints already has its service-role policy
-- (migration 174). No new table.

alter table public.mock_generated_blueprints
  drop constraint if exists mock_generated_blueprints_source_check;

alter table public.mock_generated_blueprints
  add constraint mock_generated_blueprints_source_check
  check (source in (
    'exam_realistic',
    'personalized',
    'pyq_practice_paper',
    'pyq_practice_section',
    'pyq_practice_topic'
  ));

-- Reload PostgREST schema cache so the new constraint is visible immediately.
select pg_notify('pgrst', 'reload schema');
